import express from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import router from './route.js';
import Connection from './database/db.js';
const app = express();
app.use(bodyParser.json({extended: true }));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
app.use('/', router);
const PORT = '8080';
Connection();
app.listen(PORT, () => console.log(`Server is running successfully on PORT ${PORT}`));